### ISSUE TITLE
(Mars) Commpod not working as expected

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#61]
Expected Behaviour:
1. Use Artifact
2. Choose <x> Mars cards to be revealed from hand.
3. Choose <x> in play Mars creatures.
4. Choices from step 3 are readied on the playfield.

Actual Behaviour:
1. Use Artifact
2. Choose <x> Mars cards to be revealed from hand.
3. Choose <x> in play Mars creatures.
4. Server error occurs:

```
error:  message=Cannot read property 'getEventArray' of null, stack=TypeError: Cannot read property 'getEventArray' of null
node_1   |     at SimpleStep.continueFunc (/usr/src/node/server/game/GameActions/SequentialForEachAction.js:40:97)
node_1   |     at SimpleStep.continue (/usr/src/node/server/game/gamesteps/simplestep.js:10:21)
node_1   |     at GamePipeline.continue (/usr/src/node/server/game/gamepipeline.js:105:36)
node_1   |     at EventWindow.continue (/usr/src/node/server/game/gamesteps/basestepwithpipeline.js:37:42)
node_1   |     at GamePipeline.continue (/usr/src/node/server/game/gamepipeline.js:105:36)
node_1   |     at AbilityResolver.continue (/usr/src/node/server/game/gamesteps/basestepwithpipeline.js:37:42)
node_1   |     at GamePipeline.continue (/usr/src/node/server/game/gamepipeline.js:105:36)
node_1   |     at EventWindow.continue (/usr/src/node/server/game/gamesteps/basestepwithpipeline.js:37:42)
node_1   |     at GamePipeline.continue (/usr/src/node/server/game/gamepipeline.js:105:36)
node_1   |     at MainPhase.continue (/usr/src/node/server/game/gamesteps/basestepwithpipeline.js:37:42)
node_1   |     at GamePipeline.continue (/usr/src/node/server/game/gamepipeline.js:105:36)
node_1   |     at Game.continue (/usr/src/node/server/game/game.js:916:31)
node_1   |     at /usr/src/node/server/gamenode/gameserver.js:410:26
node_1   |     at GameServer.runAndCatchErrors (/usr/src/node/server/gamenode/gameserver.js:150:13)
node_1   |     at GameServer.onGameMessage (/usr/src/node/server/gamenode/gameserver.js:407:14)
node_1   |     at Socket.onSocketEvent (/usr/src/node/server/socket.js:53:13)
node_1   |     at Socket.emit (events.js:203:13)
node_1   |     at Socket.EventEmitter.emit (domain.js:471:20)
node_1   |     at /usr/src/node/node_modules/socket.io/lib/socket.js:528:12
node_1   |     at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by Achocholacek** [comment]
I took a stab at it but get the same issue. Not sure why.

**Comment by cryogen** [comment]
Ah, I haven’t applied the fix for this. Thanks for the reminder

**Comment by cryogen** [comment]
I fixed this before go live
